development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: workspace_development
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
        #<% ENV['MONGO_HOST'] ||= "localhost:27017" %>
      options:
       


  # Configure Mongoid specific options. (optional)
  options:
   
test:
  clients:
    default:
      database: workspace_test
      hosts:
        # - <% ENV['MONGO_HOST'] ||= "localhost:27017" %>
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <% ENV['MLAB_URI'] %>
      options:
        connect_timeout: 15